mobile_data = [
    {'product_name': 'Honor',
    'image': 'https://m.media-amazon.com/images/I/61odeXsEOZL._SY879_.jpg',
    'rating': '4',
    'product_description': 'Tomorrow is here! Covered by 3 years of updates and 2 years of warranty.',
    'battery': '3000',
    'price': '21984',
    'ram': '4 GB',
    'color': 'black',
    'display_size': '6.2 inch',
    'camera': '20 mpx',
    'storage': '64 GB'},

    {'product_name': 'Infinix Smart 6 Plus ',
    'image': 'https://m.media-amazon.com/images/I/61odeXsEOZL._SY879_.jpg',
    'rating': '3',
    'product_description': 'Infinix Smart 6 Plus (Tranquil Sea Blue, 3GB RAM 64GB Storage)',
    'battery': '5000 mAh Lithium-ion Polymer Battery',
    'price': ' 8825',
    'ram': '3 GB ',
    'color': 'Tranquil Sea Blue',
    'display_size': '17.32 cm (6.82 inch) HD+ Display',
    'camera': '8 MP + Depth Lens | 5MP Front Camera',
    'storage': '64 GB'},

    {'product_name': 'Vevo Y12',
    'image': 'https://m.media-amazon.com/images/I/41yNjO-pzKL.jpg',
    'rating': '4',
    'product_description': 'Vevo Y12 (Aqua Blue, 3GB RAM, 64GB Storage) (2)',
    'battery': '18W fast charging with 5000mAh battery (Type-C)',
    'price': '15999',
    'ram': '3 GB ',
    'color': 'Aqua Blue',
    'display_size': '15.32 cm (5.82 inch) HD+ Display',
    'camera': '5 MP + Depth Lens',
    'storage': ' 64 GB '},
    
     {'product_name': 'Infinix Smart 7 Plus ',
    'image': 'https://m.media-amazon.com/images/I/61odeXsEOZL._SY879_.jpg',
    'rating': '5',
    'product_description': 'Infinix Smart 6 Plus (Tranquil Sea Blue, 3GB RAM 64GB Storage)',
    'battery': '5000 mAh Lithium-ion Polymer Battery',
    'price': ' 8825',
    'ram': '3 GB ',
    'color': 'Tranquil Sea Blue',
    'display_size': '17.32 cm (6.82 inch) HD+ Display',
    'camera': '8 MP + Depth Lens | 5MP Front Camera',
    'storage': '64 GB'},

     {'product_name': 'iQOO Z6 Lite 5G ',
    'image': 'https://m.media-amazon.com/images/I/61VbKHdE0rL._SX679_.jpg',
    'rating': '2',
    'product_description': 'Worlds First Snapdragon 4 Gen 1 Processor, that allows you to level up your performance with confidence through its efficient 6nm Process.',
    'battery': '5000 mAh Lithium-ion Polymer Battery',
    'price': ' 15825',
    'ram': '4 GB ',
    'color': 'Stellar Green',
    'display_size': '17.32 cm (6.82 inch) HD+ Display',
    'camera': '8 MP + Depth Lens | 5MP Front Camera',
    'storage': '64 GB'},

    {'product_name': 'Samsung Galaxy M53 5G',
    'image': 'https://m.media-amazon.com/images/I/810Rscvmd4L._SX679_.jpg',
    'rating': '4',
    'product_description': 'Samsung Galaxy M53 5G (Mystique Green, 6GB, 128GB Storage) | 108MP | sAmoled+ 120Hz | 12GB RAM with RAM Plus | Travel Adapter to be Purchased Separately',
    'battery': 'Massive 5000 mAh Battery',
    'price': ' 26499',
    'ram': '12 GB ',
    'color': ' Mystique Green',
    'display_size': '6.7-inch Super AMOLED Plus Display',
    'camera': ' 108MP',
    'storage': '6 GB '},

     {'product_name': 'Lava Blaze 5G ',
    'image': 'https://m.media-amazon.com/images/I/51EknP3PutL._SX679_.jpg',
    'rating': '3',
    'product_description': 'Supports All India 5G Bands - All sub-6mm-wave bands being auctioned and bought by Operators in India',
    'battery': '5000 mAh  Battery',
    'price': ' 10000',
    'ram': '3 GB ',
    'color': 'Glass Green',
    'display_size': '6.5 inch(16.5cm) HD',
    'camera': '8 MP + Depth Lens | 5MP Front Camera',
    'storage': '32 GB'},

     {'product_name': 'Lava A5 ',
    'image': 'https://m.media-amazon.com/images/I/61+ITuvLG+L._SY879_.jpg',
    'rating': '4',
    'product_description': 'Lava A5 (Gold), Military Grade Certified with 3 Days Battery Backup, Sound Leakage Resistance, Super Battery Mode, Keypad Mobile',
    'battery': '1000mAH lithium-ion battery',
    'price': ' 1409',
    'ram': '1 GB ',
    'color': 'Gold',
    'display_size': '2.4-inch',
    'camera': '0.3MP primary camera',
    'storage': '32 GB'},

     {'product_name': 'Tecno Spark 9 ',
    'image': 'https://m.media-amazon.com/images/I/91BSflfKpJL._AC_CR0%2C0%2C0%2C0_SX615_SY462_.jpg',
    'rating': '5',
    'product_description': 'Upto 7GB larger RAM (4GB LPDDR4x + 3GB Virtual RAM) with the help of memory fusion technology ',
    'battery': '5000mAh battery with up to 30 days long standby',
    'price': ' 9825',
    'ram': '  11 GB ',
    'color': 'SKY',
    'display_size': ' 6.6" HD+',
    'camera': '13MP rear Dual Camera | 5MP Front Camera',
    'storage': '64 GB'},

     {'product_name': 'A to Z Don Mobile',
    'image': 'https://m.media-amazon.com/images/I/41GaRzwNn0L.jpg',
    'rating': '4',
    'product_description': 'A to Z Don Mobile Y75 5G(8GB,128GB) Glowing Galaxy',
    'battery': '18W fast charging with 5000mAh batter',
    'price': ' 13499',
    'ram': '8 GB',
    'color': 'Tranquil sky  Blue',
    'display_size': '17.32 cm (6.82 inch) HD+ Display',
    'camera': '8 MP + Depth Lens | 5MP Front Camera',
    'storage': '64 GB'},

    {'product_name': 'Z to A Node Mobile',
    'image': 'https://m.media-amazon.com/images/I/41GaRzwNn0L.jpg',
    'rating': '3',
    'product_description': 'A to Z Don Mobile Y75 5G(8GB,128GB) Glowing Galaxy',
    'battery': '18W fast charging with 5000mAh batter',
    'price': ' 13499',
    'ram': '8 GB',
    'color': 'Tranquil sky  Blue',
    'display_size': '17.32 cm (6.82 inch) HD+ Display',
    'camera': '8 MP + Depth Lens | 5MP Front Camera',
    'storage': '64 GB'}
     
]
 
