# Generated by Django 4.1.3 on 2022-11-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('product_description', models.CharField(max_length=200)),
                ('battery', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('ram', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('display_size', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('order_time', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[('upi', 'Upi'), ('gpay', 'Gpay'), ('phonepay', 'PhonePay'), ('paytm', 'Paytm')], max_length=50)),
                ('country', models.CharField(choices=[('india', 'India'), ('usa', 'Usa'), ('indonesia', 'Indonesia'), ('mexico', 'Mexico'), ('spain', 'Spain')], max_length=100)),
                ('address_line_1', models.TextField()),
                ('address_line_2', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobcart.products')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobcart.orders')),
            ],
        ),
    ]
