# Generated by Django 4.1.3 on 2022-11-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobcart', '0002_remove_orders_address_line_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
