# Generated by Django 4.1.3 on 2022-11-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobcart', '0006_remove_cart_order_id_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='products',
        ),
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(to='mobcart.products'),
        ),
    ]
